version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

    networks:
      - monitor-net

  node-exporter:
    image: prom/node-exporter
    container_name: monitoring-node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitor-net

volumes:
  grafana-storage:


networks:
  monitor-net:
    driver: bridge
